### ISSUE TITLE
XMLRPC boolean encoding

### ISSUE THREAD

**Issue by frln** [scripting/xml-rpc#8]
The client library will encode the boolean like `<boolean> true </boolean>` but the spec give `<boolean> 1 </boolean>` as an example. Should an XMLRPC server support both encoding?

**Comment by frln** [comment]
I need to test this but I think that the standard xmlrpc library of python will only accept 1 and 0 for boolean
https://github.com/python/cpython/blob/3.7/Lib/xmlrpc/client.py#L722

**Comment by scripting** [comment]
At this stage, almost 20 years since the protocol was invented, you should start with the spec, and if you're not sure how to proceed, look at the examples in the spec and do what they do. Because that's likely what the people who came before did. 

If it's still not clear, I'd look at the Python implementation as you're doing, also PHP or Java.

I have just published a JavaScript implementation (it's in this repo), and I checked, it generates the literal "true" for true and "false" for false. 

But it's very new, and I don't know of anyone who has deployed with it, so I could change it.

**Comment by frln** [comment]
My first message was unclear, I'm actually trying to use the javascript client implementation to interact with the external api of [Odoo](https://www.odoo.com/documentation/11.0/webservices/odoo.html), an ERP that apparently use the python library for managing XMLRPC request. The server threw at me an internal error that was fixed by changing the encoding from true/false to 1/0.

After some research, it seems that only [PHP](https://github.com/gggeek/phpxmlrpc/blob/master/doc/manual/phpxmlrpc_manual.adoc#boolean) handle both true and 1. This [Apache](https://ws.apache.org/xmlrpc/types.html) library documentation only mention 0 and 1 for boolean. And as stated [above](https://github.com/python/cpython/blob/3.7/Lib/xmlrpc/client.py#L722) it seems that the python library only accept 0 and 1 without throwing an error.

**Comment by scripting** [comment]
I figured it was something like that. :-)
